# Generated by Django 4.2.11 on 2024-05-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desc',
            new_name='description',
        ),
    ]
