# Generated by Django 4.2.11 on 2024-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_handler', '0002_rename_desc_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='port',
            field=models.IntegerField(blank=True, help_text='contains port for websocket connection', null=True),
        ),
    ]
